image: ruby:2.5.1
stages:
  - build

job_build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake
