module ORDERCOSTS
  INDIVIDUAL_ORDER = 100
  COUPLE_ORDER = 175
  FAMILY_ORDER = 250
end

module ORDERSIZE
  INDIVIDUAL_ORDER = 1
  COUPLE_ORDER = 2
  FAMILY_ORDER = 3
end

module ORDERBASETIME
  INDIVIDUAL_ORDER = 10
  COUPLE_ORDER = 15
  FAMILY_ORDER = 20
end
